# Sample properties used by Spring configuration in ApplicationConfig.
#server.servlet.context-path=/api/
#dataSource
spring:
  datasource:
#    url: jdbc:mysql://mydb.c1vk5onpb4ci.eu-west-1.rds.amazonaws.com:3306/LiftChina #jdbc:mysql://localhost:3306/helloWorld
    url: jdbc:mysql://localhost:3306/helloWorld
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    username: root
    password: Hfl1027==
  jpa:
    hibernate:
      ddl-auto: update #create, create-drop, validate, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  servlet:
    session:
      timeout: 30

#S3 info and IAM user access key
gkz:
  aws:
    access_key_id: AKIASWAE4MYFIR7ASNEU
    secret_access_key: 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
  s3:
    bucket: aws-codestar-eu-west-1-184693843466-na-pipe
    region: eu-west-1


#Spring security
clientId: Fulei
#fulei-secret --> Byencrypted
client-secret: $2y$04$kqr83rrcMHpwsdQiKQQurOupJptjLblPdKIGqlBadjJ15mx2gZICC
accessTokenValidititySeconds: 3600
refreshTokenValiditySeconds: 2592000
authorizedGrantTypes: password,authorization_code,refresh_token
#Stripe keys
stripe:
  keys:
    public: pk_test_8FsSEQYHkqVZ0TA93UvX59pL00Be9qct5C
    secret: sk_test_TrT5PyNiM9HBvhPUVabMNiOq00oJbGBl2p
